- name: App deploy kubernetes
  hosts: kube
  become: yes
  tasks:
    - name: App deploy
      shell: kubectl create -f https://raw.githubusercontent.com/Sanjiban2332/DevOpsClassCodes/master/KubeDeploy.yml
